sudo: false

language: node_js
notifications:
  email: false
node_js:
- stable
cache: yarn
stages:
  - test
  - name: deploy
    # Don't deploy on tags or forked repositories
    if: type = push AND fork = false
jobs:
  include:
    ### START TEST STAGE ###
    - stage: test
      script: yarn run lint
    ### END TEST STAGE ###
    ### START DEPLOY STAGE ###
    - stage: deploy
      name: "Deploy development to now.sh"
      if: branch = develop
      script: skip
      env: MONGO_URI=$DEV_MONGO_URI MONGO_SECRET=$DEV_MONGO_SECRET NOW_ALIAS=api-dev.coding.garden
      deploy:
        provider: script
        script: yarn run now:deploy
        skip_cleanup: true
        on:
          # We already filter the job above, so deployment can run on every branch that matches the if above
          all_branches: true
    - stage: deploy
      name: "Deploy staging to now.sh"
      # RegEx for Semantic Versioning: The branch will be called vX.Y.Z for staging area
      if: branch =~ /^v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)$/
      script: skip
      env: MONGO_URI=$INT_MONGO_URI MONGO_SECRET=$INT_MONGO_SECRET NOW_ALIAS=api-int.coding.garden
      deploy:
        provider: script
        script: yarn run now:deploy
        skip_cleanup: true
        on:
          all_branches: true
    - stage: deploy
      name: "Deploy production to now.sh"
      if: branch = master
      script: skip
      env: MONGO_URI=$PRD_MONGO_URI MONGO_SECRET=$PRD_MONGO_SECRET NOW_ALIAS=api.coding.garden
      deploy:
        provider: script
        script: yarn run now:deploy
        skip_cleanup: true
        on:
          all_branches: true
    ### END DEPLOY STAGE ###