sudo: false

language: node_js
notifications:
  email: false
node_js:
- stable
cache: yarn
stages:
  - test
  - name: deploy
    if: type = push \
      ( \
        branch = develop OR \
        branch =~ /^(v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)|CA-58)$/ OR \
        branch = master \
      )
jobs:
  include:
    - stage: test
      script: npm run lint
    - stage: deploy
      name: "Deploy development to now.sh"
      script: skip
      env: MONGO_URI=$DEV_MONGO_URI MONGO_PASS=$DEV_MONGO_PASS NOW_ALIAS=api-dev.coding.garden
      deploy:
        provider: script
        script: echo $MONGO_URI $MONGO_PASS $NOW_ALIAS
        skip_cleanup: true
        on:
          repo: CodingGardenCommunity/app-backend
          branch: develop
    - name: "Deploy staging to now.sh"
      script: skip
      env: MONGO_URI=$INT_MONGO_URI MONGO_PASS=$INT_MONGO_PASS NOW_ALIAS=api-int.coding.garden
      deploy:
        provider: script
        script: echo $MONGO_URI $MONGO_PASS $NOW_ALIAS
        skip_cleanup: true
        on:
          repo: CodingGardenCommunity/app-backend
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)|CA-58)$
    - name: "Deploy production to now.sh"
      script: skip
      env: MONGO_URI=$PRD_MONGO_URI MONGO_PASS=$PRD_MONGO_PASS NOW_ALIAS=api.coding.garden
      deploy:
        provider: script
        script: echo $MONGO_URI $MONGO_PASS $NOW_ALIAS
        skip_cleanup: true
        on:
          repo: CodingGardenCommunity/app-backend
          branch: master